"""add trial fields to courses and create course_templates

Revision ID: 289b68ddc05a
Revises: 185e6f3b3a06
Create Date: 2026-08-16 11:59:00.772006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289b68ddc05a'
down_revision = '185e6f3b3a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_templates',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('credit_cost', sa.Integer(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('trial_count', sa.Integer(), nullable=True),
    sa.Column('trial_fee', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trial', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('trial_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('trial_fee', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('trial_fee')
        batch_op.drop_column('trial_count')
        batch_op.drop_column('is_trial')

    op.drop_table('course_templates')
    # ### end Alembic commands ###
