"""make coach_id nullable in courses and templates

Revision ID: 50c3d5db9820
Revises: 99d959cdfb93
Create Date: 2026-08-16 12:45:44.101246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c3d5db9820'
down_revision = '99d959cdfb93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_templates', schema=None) as batch_op:
        batch_op.alter_column('coach_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('coach_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('coach_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('course_templates', schema=None) as batch_op:
        batch_op.alter_column('coach_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
