"""add student_ids to course_templates

Revision ID: 8fc42abacd08
Revises: 50c3d5db9820
Create Date: 2026-08-16 13:28:34.879672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc42abacd08'
down_revision = '50c3d5db9820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_ids', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_templates', schema=None) as batch_op:
        batch_op.drop_column('student_ids')

    # ### end Alembic commands ###
