"""create renewal_requests table

Revision ID: 99d959cdfb93
Revises: 289b68ddc05a
Create Date: 2026-08-16 12:28:30.679721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d959cdfb93'
down_revision = '289b68ddc05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('renewal_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credits_requested', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.Column('payment_proof', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='renewalstatus'), nullable=False),
    sa.Column('admin_notes', sa.String(length=500), nullable=True),
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('renewal_requests')
    # ### end Alembic commands ###
