"""add lesson_count to users

Revision ID: 9a241962b518
Revises: 8fc42abacd08
Create Date: 2026-08-17 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a241962b518'
down_revision = '8fc42abacd08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_count', sa.Integer(), nullable=False, server_default='0'))

    # Backfill existing students' 堂數 (lesson count) from their current 點數
    # (credits) so the new "how many lessons left" display isn't just 0 for
    # everyone who already has a point balance from before this migration.
    op.execute("UPDATE users SET lesson_count = credits WHERE role = 'STUDENT'")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('lesson_count', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lesson_count')
    # ### end Alembic commands ###
