"""add description, level, and preferred_venues to users

Revision ID: da84703143fb
Revises: abfbf2b545d6
Create Date: 2026-05-12 09:06:03.714004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da84703143fb'
down_revision = 'abfbf2b545d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('preferred_venues', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_venues')
        batch_op.drop_column('level')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
